# Generated by Django 2.0.4 on 2018-10-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=100)),
                ('subordinate_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('device_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=100)),
                ('suitename', models.CharField(max_length=100)),
                ('casestatus', models.CharField(max_length=100)),
                ('errorcontent', models.TextField(max_length=10000)),
                ('report_summaryid', models.CharField(max_length=100)),
                ('caseRunningtime', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('apptype', models.CharField(max_length=100)),
                ('request_data', models.TextField(max_length=10000)),
                ('response_results', models.TextField(max_length=20000)),
                ('activity_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Key_repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('key_value', models.CharField(max_length=100)),
                ('key_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('scenario_name', models.CharField(max_length=100)),
                ('plan_id', models.CharField(max_length=100)),
                ('testcase_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report_summary',
            fields=[
                ('report_summaryid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='report_summaryid')),
                ('Starttime', models.CharField(max_length=255)),
                ('Endtime', models.CharField(max_length=255)),
                ('Runningtime', models.CharField(max_length=255)),
                ('failures', models.CharField(max_length=255)),
                ('Run', models.CharField(max_length=255)),
                ('errors', models.CharField(max_length=255)),
                ('passs', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('Battery', models.CharField(max_length=255)),
                ('casetype', models.CharField(max_length=255)),
                ('caseid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reportlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('Creation_time', models.DateTimeField()),
                ('apptype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('app', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=45)),
                ('find_by', models.CharField(max_length=100)),
                ('find_by_value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Run_time_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('activity_id', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subordinate_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subordinates_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subordinate_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=111)),
                ('test_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100)),
                ('testcase_name', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=45)),
                ('project_name', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=45)),
                ('environment', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Teststep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=100)),
                ('which', models.CharField(max_length=100)),
                ('what', models.CharField(max_length=1000)),
                ('expected', models.CharField(max_length=1000)),
                ('check_type', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teststep_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=50)),
                ('which', models.TextField(max_length=10000)),
                ('expected', models.TextField(max_length=10000)),
                ('check_type', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('headers', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
                ('parameters', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teststep',
            unique_together={('case_id', 'step_name')},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('scenario_name', 'testcase_name')},
        ),
        migrations.AlterUniqueTogether(
            name='plan_case',
            unique_together={('plan_id', 'case_id')},
        ),
        migrations.AlterUniqueTogether(
            name='key_repository',
            unique_together={('key_name', 'key_value')},
        ),
    ]
